# Generated by Django 5.1.15 on 2026-02-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunsetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('sunset_time_utc', models.DateTimeField()),
                ('golden_hour_start_utc', models.DateTimeField()),
                ('cloud_cover_total', models.FloatField()),
                ('cloud_cover_low', models.FloatField()),
                ('cloud_cover_mid', models.FloatField()),
                ('cloud_cover_high', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('precipitation_probability', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField()),
                ('quality_label', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('great', 'Great'), ('epic', 'Epic')], max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='locations.location')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
    ]
