# Generated by Django 5.1.15 on 2026-02-20 22:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('horizon_elevation_west', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['point'], name='locations_l_point_835bb1_idx')],
            },
        ),
    ]
